Fix the error openr cli command under kvstore for "interfaces" keyword
Summary:
Interface information was no longer published to kvstore and `InterfacesCmd` datastructure is no longer used.

Need to remove this cli option since we are hitting issues when running against:
```
[xiangxu1121@devvm477.ftw1 ~/fbsource/fbcode/openr] breeze -H 2401:db00:3110:9018:feed:206:e00:1 kvstore interfaces
Traceback (most recent call last):
  File "/mnt/xarfuse/uid-183877/b67aded0-ns-4026531840/__run_xar_main__.py", line 151, in <module>
    __invoke_main()
  File "/mnt/xarfuse/uid-183877/b67aded0-ns-4026531840/__run_xar_main__.py", line 148, in __invoke_main
    runpy._run_module_as_main(module, False)
  File "/usr/local/fbcode/platform007/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/fbcode/platform007/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "openr/cli/breeze.py", line 143, in <module>
  File "openr/cli/breeze.py", line 139, in main
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 27, in new_func
  File "openr/cli/clis/kvstore.py", line 158, in interfaces
AttributeError: module 'openr.cli.commands.kvstore' has no attribute 'InterfacesCmd'
```

Check with folks and need to remove "interfaces" keyword from kvstore cli option.

Reviewed By: saifhhasan

Differential Revision: D15285658

fbshipit-source-id: f153dae03c08983411ccc917cadf83d929fd0046