support data structure with copy constructor deleted
Summary:
`std::optional<T>::operator=` assignment operator attempts to call copy instead of perfect assignment by move.

Use `std::optional<T>::emplace` to ensure move constructor is used.

Add UT to capture this issue, class with const field have copy constructor deleted, compiler throws error.
```
  // class with const field
  class A {
   public:
    const std::string a;
    A(std::string&& a) : a(std::move(a)) {}
  };
```

```
In file included from openr/messaging/Queue.h:185:
openr/messaging/Queue-inl.h:73:22: error: object of type 'std::optional<A>' cannot be assigned because its copy assignment operator is implicitly deleted
    pendingRead.data = std::forward<ValueTypeT>(val);
                     ^
openr/messaging/tests/QueueTest.cpp:71:5: note: in instantiation of function template specialization 'openr::messaging::RWQueue<A>::push<A>' requested here
  q.push(A("a"));
    ^
third-party-buck/platform009/build/libgcc/include/c++/9.x/optional:658:7: note: copy assignment operator of 'optional<A>' is implicitly deleted because base class '_Enable_copy_move<is_copy_constructible_v<A>, __and_v<is_copy_constructible<A>, is_copy_assignable<A> >, is_move_constructible_v<A>, __and_v<is_move_constructible<A>, is_move_assignable<A> >, optional<A> >' has a deleted copy assignment operator
      private _Enable_copy_move<
      ^
third-party-buck/platform009/build/libgcc/include/c++/9.x/bits/enable_special_members.h:244:5: note: 'operator=' has been explicitly marked deleted here
    operator=(_Enable_copy_move const&) noexcept                    = delete;
    ^
```

Reviewed By: xiangxu1121

Differential Revision: D31697750

fbshipit-source-id: 3337ca900d71231390323241ddda826d6e099612