Fix external build unused parameter compilation error
Summary:
Address compilation error for qemu and nbg6817

```
| /tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++  -DENABLE_SYSTEMD_NOTIFY -DLINUX -Dopenrlib_EXPORTS -I/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/fbcode -Ithrift-out -I/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot/usr/include/libnl3 -mfpu=neon-vfpv4 -mfloat-abi=softfp -mcpu=cortex-a15 -fstack-protector-strong   -Wformat -Wformat-security -Werror=format-security  --sysroot=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot  -Og -g -feliminate-unused-debug-types -fmacro-prefix-map=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0=/usr/src/debug/openr/1.0.0-r0                      -fdebug-prefix-map=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0=/usr/src/debug/openr/1.0.0-r0                      -fdebug-prefix-map=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -mfpu=neon-vfpv4 -mfloat-abi=softfp -mcpu=cortex-a15 -fstack-protector-strong   -Wformat -Wformat-security -Werror=format-security  --sysroot=/tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/recipe-sysroot  -fPIC -Wno-noexcept-type -Wno-psabi -faligned-new -Wno-unused-result -Wall -Wextra -Werror -Wno-noexcept-type -Wno-maybe-uninitialized -Wno-deprecated-declarations -g -fPIC   -std=gnu++14 -MD -MT CMakeFiles/openrlib.dir/openr/plugin/Plugin.cpp.o -MF CMakeFiles/openrlib.dir/openr/plugin/Plugin.cpp.o.d -o CMakeFiles/openrlib.dir/openr/plugin/Plugin.cpp.o -c /tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/fbcode/openr/plugin/Plugin.cpp
| /tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/fbcode/openr/plugin/Plugin.cpp: In function 'void openr::pluginStart(const openr::PluginArgs&)':
| /tmp/tmp.PrwqEq8Utd/tarball/externalbuild.tgz/._builds/nbg6817/tmp/work/cortexa15-neon-vfpv4-poky-linux-gnueabi/openr/1.0.0-r0/fbcode/openr/plugin/Plugin.cpp:12:31: error: unused parameter 'pluginArgs' [-Werror=unused-parameter]
|  pluginStart(const PluginArgs& pluginArgs) {
```

Reviewed By: jstrizich

Differential Revision: D15749018

fbshipit-source-id: 3574ce78a7a1b20840088d015bdd68b58b8fc7fb