Remove dependency of Spark.thrift on KvStore
Summary:
Sometimes we observe some CMake build failure due to build speed difference like:

./openr/if/gen-cpp2/Spark_types.h:13:10: fatal error: openr/if/gen-cpp2/KvStore_types.h: No such file or directory
   13 | #include "openr/if/gen-cpp2/KvStore_types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Spark doesn't need to rely on KvStore to access this single param. Remove it.

P.S. I also revisit the `*.thrift` files and corresponding entries in CMakeList to make sure the include keeps the same.

Reviewed By: cooperlees

Differential Revision: D23010272

fbshipit-source-id: 0a94757600db5d55faa1aee83a97595c1ff473df