add missing header for lint
Summary:
got a weird task complaining about nettools_dcc build failure:https://www.internalfb.com/intern/testinfra/diagnostics/5066549659485708.562949978197616.1638852410/

error message:
```
openr/decision/RouteUpdate.h:168:23: error: implicit instantiation of undefined template 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
[CONTEXT]     std::stringstream ss;
[CONTEXT]                       ^
openr/decision/RouteUpdate.h:168:23: error: implicit instantiation of undefined template 'std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
[CONTEXT]     std::stringstream ss;
[CONTEXT]
```

add missing header

Differential Revision: D32975652

fbshipit-source-id: 5f426d610f91b9cefac7311486922b9ff9a37347