Fix python3 compatibility issue
Summary:
Terragraph has moved to python3 and some kvstore command executes successfully
but prints as fails as default
string has changed between pyhton 2 and 3. Python 3 uses unicode strings by
default and hence the comparison with byte strings (returned by kvstore client)
fails.
Fix it by comparing with inline byte string at two places.

~# breeze kvstore set-key e2e-network-prefix-1
fc00:cafe:babe::/48,64
Key e2e-network-prefix-1 found in KvStore w/ version 3. Overwriting with higher
version ...
Error: Failed to set key into KvStore,

Reviewed By: smaheshm

Differential Revision: D9407288

fbshipit-source-id: 5600dc6de6677ff00b25ff8d862ebab7a36f2c48